### ISSUE TITLE
为什么不用当当的esjob,而继续维护tbschedule

### ISSUE THREAD

**Issue by hadesvip** [jasonjoo2010/tbschedule#4]

**Comment by jasonjoo2010** [comment]
作为一个技术选型，本身并没有绝对，本质上只是选择的不同，相比：

1. 2012年前后就已经开始使用调度框架
2. 去中心化，侵入小，性能高（虽然没有流式支持，但比起分布式流式调度，单片本地调度有自身简单的优势）
3. 设计简单，稳定可靠

目前仅是将内部维护版本做开源化，并做一定的改进（任务抽象、存储后端等方面），整体保持轻量的原则，算是延续一下这种简单的设计思想(为了与业务自身相融合，尽量做到加包即用，支持redis等后端存储那么就可以与业务自身合并存储)。


总得来说就是另外一种选择吧，毕竟设计思想没有过时。

**Comment by jasonjoo2010** [comment]
Close due to 4.1.0 released.
