### ISSUE TITLE
请问如何打包编译？

### ISSUE THREAD

**Issue by wangshengwangsheng** [jasonjoo2010/tbschedule#5]

**Comment by wangshengwangsheng** [comment]
误会，我以为有些文件没放到maven库上。

**Comment by jasonjoo2010** [comment]
这个无修改需要是不需要打包的

maven库直接按readme引用会报错吗？

**Comment by jasonjoo2010** [comment]
Console也是开箱即用的

http://repo1.maven.org/maven2/com/yoloho/schedule/tbschedule-console/4.1.2/tbschedule-console-4.1.2-assembly.tar.gz

都在中央库了
